sudo: required
language: java
services:
- docker
jdk:
- openjdk8
notifications:
  email: false
env:
  global:
  - secure: BLNBXjr/AWofw2ismDILkFFSMWmD2msnP7RvCSPIThh5unnkgsG6uBULfbtJecowDbaTj9n+c3gl06zZDav5rx3wncGnlJ5I44QJubVR4TLyaiAi1mYNUEdhNUExbn8rkyhzLPRkVyolDhcSF5UN6C55OhGHCzZRns94QR6Aw6PZhjM7gIvytwK1ZYHkHn9aV86AiKCylYn0I5jcNfYl4B9sF61BhLtRAs47/I3To/vCpTz1SOl+qLE4bfLqWMZCGZwnjYwyhGTqsJgfD+f23MjBIJgGKnNvvfYnY/eleRQ70lW4hrHXk1DYolZqPKgCtj1ZRspMoJmqa5OoOV6dFOPajvVOJ1r6y8NEl9lYdP7OZacLWXjviBjOwSaEHkE2hLYDgzw3abgzKSFQnzi+PI4L5lfUeoAuu6SnSmjPm3oq9kUGFE/mO5KtHOe6bE4Q1Rc5SunngZFhkY7iczQWs9d33oSss2iHdTRkOzH0tbCOgmsRB7J5e4n/kAJ8EOsLIplhk6tns5Mc6MohBPuRvtmwA+KAJkkRJ/9UhvD8mOQv8T2tCGeUz8OLvWDrptsB+r3WdJQLO3Gk1wtmKedjMH+DicouuJRkpTvvr4eVlMKsZ+c3yT+pqoB7lOob6qsCPuCYMhdEkU5ImAsGKcLp/7BHHAMYNeNWhTj4Uea3VtU=
  - secure: D2x2BrOB4QQmgjfP600nP28sknKa9Nziv3SpxLfH+9GsZDtsI2HrR+pn8y/FveAbWbtisFT/vGpiIWz7525ukyNzJBA4S7ht2Ef9L4Y3n/fukDo2A3Q+EGlhRX/SE7+1YTcmMrtdo52e82tcCcsSpR5839xDuxJ2oKAYv1oYFQvcwGF9Hb9QMYUt5G4JMvdAhDXjDl44I8i2FgaVNesKqYSQV62O9/Rip7GQrFWs5O0qL/uij/l63eLhuEEkY6zs+IXsGeX2tKacybTKyZacRhqr+qBJj3wkE3lp/4/MCgvgv8PHg9fWHOBuZu55iyc1VMsV06IvJyNfPzFmwDZOew3dXKMfDqtAxkUMquOidJpkJL6kII4LxVmvsthDlZdk4GN/e2GPSSDh92tu49Qa3gEnlyw1BTFvm38WdWKLW7IcJ2SPTOKCKlVzuGHXh8qZf6s1dTeO6s3N7vFrPaxgWH5nhWppL9Fjo2tAwpLSKNGh/X/BBaATQ3sfTWKzgwdl2g2AEqfwTjBQ3G397L3dN+oICgOJVniL3+fia3zCAh+7k/y2E/C2DBZXq8ofrC/SEwrHzfqFOuQrx3IVG9p1NqaCPhF4tBVnkGH0qxt/th8tfKd1APXgC4S36ayMWzwAKOtBVRIZBW3sIB1W/0zShPM29F8CcbGRa3SMqlO0iVg=
script: ".travis/build_script.sh"
after_success: ".travis/push_script.sh"
